# ############################################################################
# Model: E2E ASR with attention-based ASR
# Encoder: CRDNN model
# Decoder: GRU + beamsearch + RNNLM
# Tokens: BPE with unigram
# losses: CTC+ NLL
# Training: Librispeech 960h
# Authors:  Ju-Chieh Chou, Mirco Ravanelli, Abdel Heba, Peter Plantinga 2020
# ############################################################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 19
__set_seed: !apply:torch.manual_seed [!ref <seed>]
input_type: clean_wav
output_folder: !ref results/<input_type>/<seed>
wer_file: !ref <output_folder>/wer.txt
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt
lm_ckpt_file: https://www.dropbox.com/s/wop14orl69gakhl/model.ckpt?dl=1

# Tokenizer model
tok_mdl_file: https://www.dropbox.com/s/o7gnouwdoqchotj/1000_unigram.model?dl=1
tok_voc_file: https://www.dropbox.com/s/7l8z622cpd3t8st/1000_unigram.vocab?dl=1

# Model for clean pre-training
model_ckpt_file: https://www.dropbox.com/s/bb209th9vcs555j/model.ckpt?dl=1
norm_ckpt_file: https://www.dropbox.com/s/ib20ub7liaqcirw/normalizer.ckpt?dl=1

# Data files
data_folder: !PLACEHOLDER # e.g., /localscratch/noisy-vctk-16k
data_folder_rirs: !ref <data_folder>
train_annotation: !ref <data_folder>/train.json
valid_annotation: !ref <data_folder>/valid.json
test_annotation: !ref <data_folder>/test.json
skip_prep: False

# Training parameters
number_of_epochs: 30
number_of_ctc_epochs: 0
batch_size: 8
lr: 0.0001
ctc_weight: 0.5
token_type: unigram  # ["unigram", "bpe", "char"]
sorting: ascending
character_coverage: 1.0
dataloader_options:
    batch_size: !ref <batch_size>

# Feature parameters
sample_rate: 16000
n_fft: 400
n_mels: 40
output_neurons: 1000  # index(blank/eos/bos) = 0
blank_index: 0
unk_index: 0
bos_index: 0
eos_index: 0

# Decoding parameters
min_decode_ratio: 0.0
max_decode_ratio: 1.0
beam_size: 80
eos_threshold: 10
using_max_attn_shift: True
max_attn_shift: 240
lm_weight: 0.15
coverage_penalty: 1.5
temperature: 1.25
temperature_lm: 1.25

asr_model: !include:models/asr_model.yaml
    n_mels: !ref <n_mels>
    dropout_rate: 0.15
    output_neurons: !ref <output_neurons>

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

normalizer: !new:speechbrain.processing.features.InputNormalization
    norm_type: global

compute_features: !new:speechbrain.lobes.features.Fbank
    sample_rate: !ref <sample_rate>
    n_fft: !ref <n_fft>
    n_mels: !ref <n_mels>

env_corrupt: !new:speechbrain.lobes.augment.EnvCorrupt
    openrir_folder: !ref <data_folder_rirs>
    babble_prob: 0.0
    reverb_prob: 0.0
    noise_prob: 1.0
    noise_snr_low: 0
    noise_snr_high: 15

augmentation: !new:speechbrain.lobes.augment.TimeDomainSpecAugment
    sample_rate: !ref <sample_rate>
    speeds: [95, 100, 105]

log_softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

ctc_cost: !name:speechbrain.nnet.losses.ctc_loss
    blank_index: !ref <blank_index>

seq_cost: !name:speechbrain.nnet.losses.nll_loss
    label_smoothing: 0.1

modules:
    enc: !ref <asr_model[src_embedding]>
    emb: !ref <asr_model[tgt_embedding]>
    dec: !ref <asr_model[recognizer]>
    ctc_lin: !ref <asr_model[ctc_output]>
    seq_lin: !ref <asr_model[seq_output]>
    lm_model: !ref <asr_model[lm_model]>
    normalizer: !ref <normalizer>

model: !new:torch.nn.ModuleList
    - - !ref <asr_model[src_embedding]>
      - !ref <asr_model[tgt_embedding]>
      - !ref <asr_model[recognizer]>
      - !ref <asr_model[ctc_output]>
      - !ref <asr_model[seq_output]>

beam_searcher: !new:speechbrain.decoders.seq2seq.S2SRNNBeamSearchLM
    embedding: !ref <asr_model[tgt_embedding]>
    decoder: !ref <asr_model[recognizer]>
    linear: !ref <asr_model[seq_output]>
    language_model: !ref <asr_model[lm_model]>
    bos_index: !ref <bos_index>
    eos_index: !ref <eos_index>
    min_decode_ratio: !ref <min_decode_ratio>
    max_decode_ratio: !ref <max_decode_ratio>
    beam_size: !ref <beam_size>
    eos_threshold: !ref <eos_threshold>
    using_max_attn_shift: !ref <using_max_attn_shift>
    max_attn_shift: !ref <max_attn_shift>
    coverage_penalty: !ref <coverage_penalty>
    lm_weight: !ref <lm_weight>
    temperature: !ref <temperature>
    temperature_lm: !ref <temperature_lm>

opt_class: !name:torch.optim.AdamW
    lr: !ref <lr>
    weight_decay: 0.00005

lr_annealing: !new:speechbrain.nnet.schedulers.NewBobScheduler
    initial_value: !ref <lr>
    improvement_threshold: 0.0025
    annealing_factor: 0.7
    patient: 0

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        model: !ref <model>
        scheduler: !ref <lr_annealing>
        normalizer: !ref <normalizer>
        counter: !ref <epoch_counter>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>

error_rate_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats

cer_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats
    split_tokens: True
