# ################################
# Model: Speaker Verification Baseline
# Authors: Hwidong Na 2020
#          Mirco Ravanelli 2020
# ################################

seed: 1234
__set_seed: !apply:torch.manual_seed [!ref <seed>]

# Folders and train_log file
voxceleb_source: /network/datasets/restricted/voxceleb_users/voxceleb/voxceleb1
data_folder: /localscratch/voxceleb1
output_folder: results/voxceleb1_2/speaker_verification_ecapa_big
save_folder: !ref <output_folder>/save/
device: 'cuda:0'

# Pretrain from web (as an alternative specify a file)
embedding_param: https://www.dropbox.com/s/ct72as3hapy8kb5/ecapa_big.yaml?dl=1

# Use the following links for the official voxceleb splits:
# VoxCeleb1 (cleaned): https://www.robots.ox.ac.uk/~vgg/data/voxceleb/meta/veri_test2.txt
# VoxCeleb1-H (cleaned): https://www.robots.ox.ac.uk/~vgg/data/voxceleb/meta/list_test_hard2.txt
# VoxCeleb1-E (cleaned): https://www.robots.ox.ac.uk/~vgg/data/voxceleb/meta/list_test_all2.txt.
# VoxCeleb1-E and VoxCeleb1-H lists are drawn from the VoxCeleb1 training set.
# Therefore you cannot use any files in VoxCeleb1 for training if you are using these lists for testing.
verification_file: https://www.robots.ox.ac.uk/~vgg/data/voxceleb/meta/veri_test2.txt


# csv files
train_data: !ref <save_folder>/train.csv
enrol_data: !ref <save_folder>/enrol.csv
test_data: !ref <save_folder>/test.csv

batch_size: 32
score_norm: 's-norm' # z-norm t-norm s-norm none
cohort_size: 20000 # amount of imposter utterances in normalization cohort
n_train_snts: 300000 # used for normalization stats

# Feature parameters
n_mels: 80
left_frames: 0
right_frames: 0
deltas: False

# Dataloader options
train_dataloader_opts:
    batch_size: !ref <batch_size>

enrol_dataloader_opts:
    batch_size: !ref <batch_size>

test_dataloader_opts:
    batch_size: !ref <batch_size>

embedding_model: !new:recipes.VoxCeleb.SpeakerRec.pretrained.pretrained.Verification
    hparams_file: !ref <embedding_param>
    save_folder: !ref <save_folder>
